[package]
name = "all"
version = "0.1.0"
edition = "2021"
target = ["x86_64-pc-windows-msvc"]

[dependencies]
windows = { version = "0.58.0", features = ["Win32_Devices_FunctionDiscovery", "Win32_Graphics_Gdi", "Win32_Media_Audio", "Win32_System_Com", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Power", "Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_UI_Shell_PropertiesSystem", "Win32_UI_WindowsAndMessaging"] }
windows-core = "0.58.0"
